[package]
name = "monitor-box-daemon"
version = "0.1.0"
authors = ["alexesmet <alexes.met@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.15.1"
serialport = "3.3.0"
